apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kaboom
  name: kaboom
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kaboom
status:
  loadBalancer: {}
